// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvdVuaIOWJwLAOb8Lp2YLT2dedfp45gg',
    appId: '1:297968121277:web:ba59b26ab136b998c8ced4',
    messagingSenderId: '297968121277',
    projectId: 'aile-hekimligi-72909',
    authDomain: 'aile-hekimligi-72909.firebaseapp.com',
    storageBucket: 'aile-hekimligi-72909.appspot.com',
    measurementId: 'G-K9N2J4212Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBwlKr1RCfXu43G59mWmsNTFU3CjZZ3U',
    appId: '1:297968121277:android:583fe0fd12142981c8ced4',
    messagingSenderId: '297968121277',
    projectId: 'aile-hekimligi-72909',
    storageBucket: 'aile-hekimligi-72909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl0KVZ-mLkKdHexesZFUBUcUhTBJzX8kk',
    appId: '1:297968121277:ios:1acc1a02a1d48c25c8ced4',
    messagingSenderId: '297968121277',
    projectId: 'aile-hekimligi-72909',
    storageBucket: 'aile-hekimligi-72909.appspot.com',
    iosClientId: '297968121277-kuvdo56k8thomdddt9gr25iab75c0s8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aileHekimligiUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl0KVZ-mLkKdHexesZFUBUcUhTBJzX8kk',
    appId: '1:297968121277:ios:1acc1a02a1d48c25c8ced4',
    messagingSenderId: '297968121277',
    projectId: 'aile-hekimligi-72909',
    storageBucket: 'aile-hekimligi-72909.appspot.com',
    iosClientId: '297968121277-kuvdo56k8thomdddt9gr25iab75c0s8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aileHekimligiUygulamasi',
  );
}
